# Generated by Django 3.1.1 on 2020-09-28 06:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('doctor_name', models.CharField(max_length=225)),
                ('doctor_password', models.CharField(max_length=225)),
                ('doctor_email', models.CharField(max_length=225)),
                ('doctor_dob', models.DateField()),
                ('doctor_phone', models.CharField(max_length=225)),
                ('doctor_gender', models.CharField(max_length=50)),
                ('doctor_city', models.CharField(max_length=225)),
                ('doctor_state', models.CharField(max_length=225)),
                ('doctor_zipcode', models.IntegerField()),
                ('doctor_services', models.CharField(max_length=225)),
                ('doctor_qualification', models.CharField(max_length=225)),
                ('doctor_Field', models.CharField(max_length=225)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('patient_dob', models.DateField()),
                ('patient_blood', models.CharField(max_length=50)),
                ('patient_mobile', models.CharField(max_length=225)),
                ('patient_address', models.CharField(max_length=225)),
                ('patient_city', models.CharField(max_length=225)),
                ('patient_state', models.CharField(max_length=225)),
                ('patient_zipcode', models.CharField(max_length=225)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine', models.CharField(max_length=255)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_doctor.doctor')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_doctor.patient')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_field', models.CharField(max_length=50)),
                ('date_field', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_doctor.doctor')),
                ('patient_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_doctor.patient')),
            ],
        ),
    ]
