# Generated by Django 3.1.1 on 2020-09-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_address',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_blood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_city',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_dob',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_mobile',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_state',
            field=models.CharField(max_length=225, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_zipcode',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
