# Generated by Django 3.1.1 on 2020-09-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0006_remove_doctor_doctor_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
