# Generated by Django 3.1.1 on 2020-09-29 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0009_appointment_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date_field',
            field=models.DateField(null=True),
        ),
    ]
