# Generated by Django 3.1.1 on 2020-09-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0010_auto_20200929_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
