# Generated by Django 3.1.1 on 2020-10-01 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0011_auto_20200929_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time_field',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
