# Generated by Django 3.1.1 on 2020-10-02 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0012_auto_20201001_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, default='/home/developer/Desktop/clinicmanagement system/Hospital_management-master/user_doctor/static/image/Flower_by_Dominik_Scythe.jpg', null=True, upload_to=''),
        ),
    ]
