# Generated by Django 3.1.1 on 2020-10-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0013_auto_20201002_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, default='Hospital_management-master/user_doctor/static/image/Flower_by_Dominik_Scythe_rIdzoSN.jpg', null=True, upload_to=''),
        ),
    ]
