# Generated by Django 3.1.1 on 2020-10-02 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0014_auto_20201002_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, default='static/image/Flower_by_Dominik_Scythe_rIdzoSN.jpg', null=True, upload_to=''),
        ),
    ]
