# Generated by Django 3.1.1 on 2020-10-02 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0015_auto_20201002_0707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, default='path/to/my/default/Balloon_by_Matt_Benson.jpg', null=True, upload_to=''),
        ),
    ]
