# Generated by Django 3.1.1 on 2020-10-03 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0016_auto_20201002_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=2500),
        ),
    ]
