# Generated by Django 3.1.1 on 2020-10-03 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0017_auto_20201003_0354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='medicine',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
