# Generated by Django 3.1.1 on 2020-10-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0019_prescription_doctor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
