# Generated by Django 3.1.1 on 2020-10-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0020_auto_20201008_1143'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_name',
            new_name='doctor_first_name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_last_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
