# Generated by Django 3.1.1 on 2020-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0021_auto_20201008_1220'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='name',
            new_name='user_name',
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_full_name',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
