# Generated by Django 3.1.1 on 2020-10-09 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0022_auto_20201008_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_image',
            field=models.ImageField(blank=True, null=True, upload_to='patient'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
