# Generated by Django 3.1.1 on 2020-10-13 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0025_auto_20201011_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_image',
            field=models.ImageField(default=0, max_length=10000, upload_to=''),
            preserve_default=False,
        ),
    ]
