# Generated by Django 3.1.1 on 2020-10-14 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0028_doctor_pat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='pat_id',
        ),
    ]
