# Generated by Django 3.1.1 on 2020-10-15 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0031_blocked_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='doctor_zipcode',
            field=models.CharField(max_length=2225),
        ),
    ]
