# Generated by Django 3.1.1 on 2020-10-19 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_doctor', '0032_auto_20201015_1156'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor_qualification',
            old_name='doctor_college',
            new_name='doctor_degree1',
        ),
        migrations.RenameField(
            model_name='doctor_qualification',
            old_name='doctor_year',
            new_name='doctor_degree2',
        ),
    ]
